<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260103201627 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, team VARCHAR(255) DEFAULT NULL, points INT DEFAULT 0 NOT NULL, rebounds INT DEFAULT 0 NOT NULL, assists INT DEFAULT 0 NOT NULL, games INT DEFAULT 0 NOT NULL, minutes_played INT DEFAULT 0 NOT NULL, fields_goals INT DEFAULT 0 NOT NULL, fields_goals_attempts INT DEFAULT 0 NOT NULL, three_fields_goals INT DEFAULT 0 NOT NULL, three_fields_goals_attempts INT DEFAULT 0 NOT NULL, free_throws INT DEFAULT 0 NOT NULL, free_throws_attempts INT DEFAULT 0 NOT NULL, offensive_rebounds INT DEFAULT 0 NOT NULL, defensive_rebounds INT DEFAULT 0 NOT NULL, steals INT DEFAULT 0 NOT NULL, blocks INT DEFAULT 0 NOT NULL, turnovers INT DEFAULT 0 NOT NULL, personal_fouls INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
