<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260116132527 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Création BDD';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE league (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, crawler_url VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, points INT DEFAULT 0 NOT NULL, assists INT DEFAULT 0 NOT NULL, games INT DEFAULT 0 NOT NULL, minutes_played INT DEFAULT 0 NOT NULL, fields_goals INT DEFAULT 0 NOT NULL, fields_goals_attempts INT DEFAULT 0 NOT NULL, three_fields_goals INT DEFAULT 0 NOT NULL, three_fields_goals_attempts INT DEFAULT 0 NOT NULL, free_throws INT DEFAULT 0 NOT NULL, free_throws_attempts INT DEFAULT 0 NOT NULL, offensive_rebounds INT DEFAULT 0 NOT NULL, defensive_rebounds INT DEFAULT 0 NOT NULL, steals INT DEFAULT 0 NOT NULL, blocks INT DEFAULT 0 NOT NULL, turnovers INT DEFAULT 0 NOT NULL, personal_fouls INT DEFAULT 0 NOT NULL, team_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98197A65296CD8AE ON player (team_id)');
        $this->addSql('CREATE TABLE team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE team_league (team_id INT NOT NULL, league_id INT NOT NULL, PRIMARY KEY (team_id, league_id))');
        $this->addSql('CREATE INDEX IDX_48AF84C1296CD8AE ON team_league (team_id)');
        $this->addSql('CREATE INDEX IDX_48AF84C158AFC4DE ON team_league (league_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
        $this->addSql('ALTER TABLE team_league ADD CONSTRAINT FK_48AF84C1296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_league ADD CONSTRAINT FK_48AF84C158AFC4DE FOREIGN KEY (league_id) REFERENCES league (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A65296CD8AE');
        $this->addSql('ALTER TABLE team_league DROP CONSTRAINT FK_48AF84C1296CD8AE');
        $this->addSql('ALTER TABLE team_league DROP CONSTRAINT FK_48AF84C158AFC4DE');
        $this->addSql('DROP TABLE league');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE team_league');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
